version: "3.9"
services:
#  clinic_service:
#    build:
#      context: ./clinic-service
#      dockerfile: Dockerfile
#    container_name: clinic-service
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      - PROFILE=docker
#    depends_on:
#      - clinic_db
  clinic_db:
    image: 'postgres'
    container_name: clinic_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=welcome1
      - POSTGRES_DB=clinic_db
