openapi: 3.0.0
info:
  title: Clinic API
  version: 0.1.9
paths:
  /users:
    post:
      operationId: updateUser
      summary: Update user name and surname
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        200:
          description: 'User is created'

  /profiles:
    get:
      operationId: getUserInfo
      summary: Return a one object list with user's profile
      responses:
        200:
          description: 'Return user information profile'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
  /login:
    post:
      operationId: login
      summary: Login user with credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /register:
    post:
      operationId: register
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        201:
          description: 'Id of created user'

components:
  schemas:
    UserRequest:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
    AuthRequest:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        token:
          type: string
    UserRegistrationRequest:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        password:
          type: string
    ProfileResponse:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        pwz:
          type: string
